### PR TITLE
Fix font feature range

### LINKED ISSUE #170: Range for add_font_feature
So, I had been using the harfbuzz feature string ranges to set feature ranges. But of course, these ranges are per run, as well as being utf32 based.

I'm going to try and see if I'm able to create a range-based function that sets the features over ranges, but doesn't break the runs. Shouldn't be too hard as hb-feature-t is just a struct, but I'm making this issue so I don't forget.

### PR DESCRIPTION
**Pull request by therahedwig**
This fixes #170, applies on to of #169 and #171

I was wrong, it's not per run, just an issue of the encoding being different between the text and the harfbuzz buffer, which makes this fix a lot simpler. This should mean that ranges used for font_feature won't need to be converted to UTF32 beforehand.

### CODE REVIEW

**Comment by therahedwig** [comment]
Also rebased this one into a single commit, so it's easier to review.

File: src/raqm.c [hunk 1]
```diff
@@ -854,6 +854,29 @@ raqm_add_font_feature (raqm_t     *rq,
     if (!new_features)
       return false;
 
+    if (fea.start != HB_FEATURE_GLOBAL_START)
+    {
+      if (rq->text_utf8)
+      {
```
Comment (khaledhosny) [inline src/raqm.c:860]: The curly brackets should be dropped for one line body.

**Review by khaledhosny — APPROVED** [review]
LGTM.

File: src/raqm.c [hunk 2]
```diff
@@ -854,6 +854,29 @@ raqm_add_font_feature (raqm_t     *rq,
...
+        fea.start = _raqm_u8_to_u32_index (rq, fea.start);
```
Comment (khaledhosny) [inline src/raqm.c:861]: We probably need a helper function or a macro that encapsulates this logic, something like `_rq_encoding_to_u32_index()` that would check the encoding and do the mapping if necessary.
